const data = [
  { "grade": "A", "name": "Suku" },
  { "grade": "B", "name": "Ravi" },
  { "grade": "C", "name": "Anjali" },
  { "grade": "D", "name": "Vikram" },
  { "grade": "A", "name": "Meena" },
  { "grade": "B", "name": "Arjun" },
  { "grade": "C", "name": "Kiran" },
  { "grade": "A", "name": "Ravi" },
  { "grade": "D", "name": "Suku" },
  { "grade": "B", "name": "Lakshmi" },
  { "grade": "A", "name": "Pradeep" },
  { "grade": "C", "name": "Manoj" },
  { "grade": "B", "name": "Sneha" },
  { "grade": "D", "name": "Vikram" },
  { "grade": "C", "name": "Meena" },
  { "grade": "A", "name": "Kavya" },
  { "grade": "B", "name": "Suresh" },
  { "grade": "A", "name": "Anjali" },
  { "grade": "C", "name": "Karthik" },
  { "grade": "D", "name": "Ravi" },
  { "grade": "B", "name": "Pooja" },
  { "grade": "A", "name": "Deepak" },
  { "grade": "C", "name": "Suku" },
  { "grade": "D", "name": "Kiran" },
  { "grade": "B", "name": "Vikram" },
  { "grade": "A", "name": "Aditi" },
  { "grade": "D", "name": "Meena" },
  { "grade": "B", "name": "Manoj" },
  { "grade": "C", "name": "Lakshmi" },
  { "grade": "A", "name": "Ravi" },
  { "grade": "D", "name": "Pradeep" },
  { "grade": "B", "name": "Sneha" },
  { "grade": "A", "name": "Arjun" },
  { "grade": "C", "name": "Kavya" },
  { "grade": "D", "name": "Pooja" },
  { "grade": "B", "name": "Suku" },
  { "grade": "A", "name": "Kiran" },
  { "grade": "C", "name": "Suresh" },
  { "grade": "D", "name": "Anjali" },
  { "grade": "B", "name": "Deepak" }
]

module.exports = data