version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - URL=${URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXP=${JWT_EXP}
      - PORT=${PORT}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - student-app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - student-app-network

networks:
  student-app-network:
    driver: bridge