name: Build and Test Node js app with CI/CD Pipeline

on: push

jobs:
  #Setting up Node js and running test cases
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
      - name: Check out
        uses: actions/checkout@v4
    
    # Setup node 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

    # Checking node version
      - name: Checking node version
        run:
          node --version
      
    # Installing all dependencies 
      - name: Install Dependencies
        run: npm install

    # Running mocha-chai test cases
      - name: Run Test Cases
        run: npm test

  docker-build-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: pipeline 

    steps:
    # Checkout the git repo
      - name: Check out
        uses: actions/checkout@v4
        
    # Building the docker image from Dockerfile
      - name: Build docker image
        run: docker build -t student-managment-api-v1-image:test .
    
    # Building and running the docker-compose
      - name: Run docker-compose
        run: |
          docker-compose up -d --build
        env:
          URL: ${{ secrets.URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXP: ${{ secrets.JWT_EXP }}
          PORT: ${{ secrets.PORT }}

    # Waiting for 10sec until the container is up running
      - name: Wait for Container to start
        run: sleep 10
    
    #To check logs in case of failure
      - name: Show container logs
        run: docker-compose logs || echo "Container exited"

    # Calling the route to check if the application was deployed properly - Will get Error - "Invalid Credentials"
      - name: Curl health endpoint
        run: |
          curl http://localhost:3000/api/students

    # Removing container and image 
      - name: Stop and remove containers
        run: |
          docker-compose down