name: Build Node Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:24

    steps:
      - name: Check out
        uses: actions/checkout@v4 

      - name: Checking node version
        run:
          node --version
          npm --version
      
      - name: Install Dependencies
        run: npm install

      - name: Run Test Cases
        run: npm test

      - name: Build docker image
        run: docker build -t student-managment-api-v1-image
