name: CI/CD Pipeline for Student Management API
on: push

jobs:
  #Setting up Node js 
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
      - name: Check out
        uses: actions/checkout@v4
    
    # Setup node 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

    # Checking node version
      - name: Checking node version
        run:
          node --version
      
    # Installing all dependencies 
      - name: Install Dependencies
        run: npm install

  docker-build-test:
    runs-on: ubuntu-latest
    needs: build
    environment: pipeline 

    steps:
    # Checkout the git repo
      - name: Check out
        uses: actions/checkout@v4

    #Install Docker-compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
    
    # Building and running the docker-compose
      - name: Run docker-compose
        run: |
          docker-compose up -d --build
        env:
          URL: ${{ secrets.URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXP: ${{ secrets.JWT_EXP }}
          PORT: ${{ secrets.PORT }}

    # Waiting for 10sec until the container is up running
      - name: Wait for Container to start
        run: sleep 15
    
    #To check logs in case of failure
      - name: Show container logs
        run: docker-compose logs 

    # Calling the route to check if the application was deployed properly - Will get Error - "Invalid Credentials"
      - name: Curl health endpoint
        run: |
          curl http://localhost:3000/api/students

    # Removing container and image 
      - name: Stop and remove containers
        if: always() # This ensures cleanup happens even if a step fails
        run: docker-compose down